version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: short-url-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - BASE_URL=http://localhost:3000
      - DB_PATH=/app/data/urls.db
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: bridge